In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_fbc1ff715a2449e39d8c683abf1696a8 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='KH93R2Bd0pnIQfNhrDv-zVwPpil9sqylslMrczI9N_DY',
    ibm_auth_endpoint="https://iam.cloud.ibm.com/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_fbc1ff715a2449e39d8c683abf1696a8.get_object(Bucket='notebookdeployment-donotdelete-pr-kkjpbhymonqutb',Key='Churn_Modelling.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body)
df.head()


RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
df['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [4]:
df.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le = LabelEncoder()
df['Geography'] = le.fit_transform(df['Geography'])
df['Gender'] = le.fit_transform(df['Gender'])
df.head()

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602  Hargrave          619          0       0   42   
1          2    15647311      Hill          608          2       0   41   
2          3    15619304      Onio          502          0       0   42   
3          4    15701354      Boni          699          0       0   39   
4          5    15737888  Mitchell          850          2       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
x = df.iloc[:,3:-1].values
y= df.iloc[:,-1].values

In [8]:
z = df.iloc[:,3:-1]
z.head(2)

CreditScore  Geography  Gender  Age  Tenure   Balance  NumOfProducts  \
0          619          0       0   42       2      0.00              1   
1          608          2       0   41       1  83807.86              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58

In [9]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [6.0800000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [5.0200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [10]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [11]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z = one.fit_transform(x[:,1:2]).toarray()
x = np.delete(x,1,axis = 1)
x=np.concatenate((z,x),axis=1)

/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [12]:
x

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [13]:
x = x[:,1:]

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [16]:
x_train.shape

(8000, 11)

In [17]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [18]:
x_train

array([[-0.5698444 ,  1.74309049,  0.16958176, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [ 1.75486502, -0.57369368, -2.30455945, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-0.5698444 , -0.57369368, -1.19119591, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [-0.5698444 , -0.57369368,  0.9015152 , ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.5698444 ,  1.74309049, -0.62420521, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [ 1.75486502, -0.57369368, -0.28401079, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [19]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [20]:
classifier = Sequential()

W0721 13:24:35.050874 139720632121152 module_wrapper.py:139] From /opt/conda/envs/Python36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [21]:
classifier.add(Dense(units=11, init='uniform', activation='relu'))

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=11, activation="relu", kernel_initializer="uniform")`
  if __name__ == '__main__':


In [22]:
classifier.add(Dense(units=6, init='uniform', activation='relu'))

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu", kernel_initializer="uniform")`
  if __name__ == '__main__':


In [23]:
classifier.add(Dense(units=1, init='uniform', activation='sigmoid'))

/opt/conda/envs/Python36/lib/python3.6/site-packages/ipykernel/__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, activation="sigmoid", kernel_initializer="uniform")`
  if __name__ == '__main__':


In [24]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

W0721 13:24:38.106545 139720632121152 module_wrapper.py:139] From /opt/conda/envs/Python36/lib/python3.6/site-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.



In [25]:
classifier.fit(x_train,y_train, batch_size=32, epochs=2)

W0721 13:24:39.506241 139720632121152 module_wrapper.py:139] From /opt/conda/envs/Python36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0721 13:24:39.522237 139720632121152 module_wrapper.py:139] From /opt/conda/envs/Python36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0721 13:24:39.570916 139720632121152 module_wrapper.py:139] From /opt/conda/envs/Python36/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3376: The name tf.log is deprecated. Please use tf.math.log instead.

W0721 13:24:39.580881 139720632121152 deprecation.py:323] From /opt/conda/envs/Python36/lib/python3.6/site-packages/tensorflow_core/python/ops/nn_impl.py:183: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Us

Epoch 1/2
8000/8000 [==============================] - 1s 109us/step - loss: 0.5701 - acc: 0.7936
Epoch 2/2
8000/8000 [==============================] - 0s 49us/step - loss: 0.4340 - acc: 0.7960


In [26]:
y_pred = classifier.predict(x_test)

In [27]:
y_pred = (y_pred>0.5)

In [28]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [29]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [30]:
from sklearn.metrics import classification_report,confusion_matrix

In [31]:
print(confusion_matrix(y_pred,y_test))
print(" ")
print(classification_report(y_pred,y_test))

[[1595  405]
 [   0    0]]
 
              precision    recall  f1-score   support

           0       1.00      0.80      0.89      2000
           1       0.00      0.00      0.00         0

   micro avg       0.80      0.80      0.80      2000
   macro avg       0.50      0.40      0.44      2000
weighted avg       1.00      0.80      0.89      2000



/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [32]:
from sklearn.metrics import accuracy_score

In [33]:
print(accuracy_score(y_pred,y_test))

0.7975


In [34]:
classifier.save('sampleannmodel.h5')

In [35]:
!tar -zcvf sampleannmodel.tgz sampleannmodel.h5

sampleannmodel.h5


In [36]:
!pip install watson_machine_learning_client

In [37]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

In [38]:
wml_credentials = {
  "apikey": "QXqREHHtU_OXaYOsL7QFgd9ln6Vkjdsvh--_0WwEf1qb",
  "iam_apikey_description": "Auto-generated for key ca15cefa-d90f-4fb0-a23b-a33f89f11007",
  "iam_apikey_name": "wdp-writer",
  "iam_role_crn": "crn:v1:bluemix:public:iam::::serviceRole:Writer",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/6c4e2f271bb347ea8f049c70f7d3f7c9::serviceid:ServiceId-078e9dc4-ba1b-42e7-a375-20c290953067",
  "instance_id": "e60afa38-72b6-4672-a1aa-cc31ac5275e4",
  "url": "https://eu-gb.ml.cloud.ibm.com"
}

In [39]:
import tensorflow

In [40]:
tensorflow.__version__

'1.15.0'

In [47]:
import sys
!{sys.executable} -m pip install tensorflow==1.15

     |████████████████████████████████| 412.3MB 98kB/s s eta 0:00:01��█▌              | 225.0MB 48.7MB/s eta 0:00:04��█▊              | 228.1MB 48.7MB/s eta 0:00:04
     |████████████████████████████████| 512kB 42.2MB/s eta 0:00:01
     |████████████████████████████████| 51kB 23.8MB/s eta 0:00:01
     |████████████████████████████████| 14.6MB 23.4MB/s eta 0:00:01
     |████████████████████████████████| 71kB 24.2MB/s eta 0:00:01
     |████████████████████████████████| 3.8MB 37.0MB/s eta 0:00:01��█████████████████████████████▍| 3.7MB 37.0MB/s eta 0:00:01
ERROR: autoai-libs 1.10.5 has requirement pandas>=0.24.2, but you'll have pandas 0.24.1 which is incompatible.
  Found existing installation: tensorflow-estimator 1.14.0
    Uninstalling tensorflow-estimator-1.14.0:
      Successfully uninstalled tensorflow-estimator-1.14.0
  Found existing installation: numpy 1.15.4
    Uninstalling numpy-1.15.4:
      Successfully uninstalled numpy-1.15.4
  Found existing installation: Keras-Applicatio

In [41]:
tensorflow.__version__

'1.15.0'

In [42]:
client = WatsonMachineLearningAPIClient(wml_credentials)

In [47]:
metadata = {
    client.repository.ModelMetaNames.DESCRIPTION: 'SAMPLE DESCRIPTION',
    client.repository.ModelMetaNames.AUTHOR_NAME: 'Poojitha',
    client.repository.ModelMetaNames.NAME: 'keras model',
    client.repository.ModelMetaNames.FRAMEWORK_NAME: 'tensorflow',
    client.repository.ModelMetaNames.FRAMEWORK_VERSION: '1.15',
    client.repository.ModelMetaNames.FRAMEWORK_LIBRARIES: [{'name':'keras','version':'2.2.4'}]
}

In [48]:
model_details = client.repository.store_model(model='sampleannmodel.tgz',meta_props=metadata)

In [49]:
model_uid = model_details['metadata']['guid']
model_deploy = client.deployments.create(artifact_uid=model_uid,name="ann")



#######################################################################################

Synchronous deployment creation for uid: '35b452ef-e927-4060-bef4-ecd2ad4c4d75' started

#######################################################################################


INITIALIZING
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='17ff03e3-acd1-4222-b0b1-2a9a1726c2c1'
------------------------------------------------------------------------------------------------




In [50]:
scoring_endpoint = client.deployments.get_scoring_url(model_deploy)

In [51]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/e60afa38-72b6-4672-a1aa-cc31ac5275e4/deployments/17ff03e3-acd1-4222-b0b1-2a9a1726c2c1/online'